version: '3'

services:
  api_postgres:
    container_name: api_postgres
    image: postgres:15.2-alpine
    # ports:
    #   - ${DATABASE_PORT}:5432
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: always

  backend:
    container_name: wetwart_backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    # volumes:
    #   - ./prisma:/app/prisma
    #   - ./node_modules:/app/node_modules
    #   - ./dist:/app/dist
    #   - /home/sfinoe/ssl:/etc/certs
    depends_on:
      - api_postgres
    env_file:
      - .env
    restart: always

  frontend:
    container_name: wetwart_frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile.frontend
    ports:
      # - 443:443
      - 80:80
    depends_on:
      - backend
    # volumes:
    #   - ../frontend/dist:/usr/share/nginx/html
    #   - /home/sfinoe/ssl:/etc/certs
    env_file:
      - .env
    restart: always
