version: '3'

services:
  api_postgres:
    container_name: api_postgres
    image: postgres:15.2-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: always

  artwart_backend:
    container_name: artwart_backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - api_postgres
    env_file:
      - .env
    restart: always

  artwart_frontend:
    container_name: artwart_frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile.frontend
    ports:
      - 80:80
    depends_on:
      - backend
    env_file:
      - .env
    restart: always
